spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306
    username: root
    password: test1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    active: local
